node {
   def nodeHome = tool "NODE_PATH"
   env.PATH="${env.PATH}:${nodeHome}/"
   
   stage("Checkout Source"){
       checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/akilans/react-node-employee.git']]])
   }
   
   stage("Install Dependencies"){
     dir('react-frontend') {
         sh 'npm install'
     }
   }
   
   stage("Code Quality"){
     dir('react-frontend') {
         sh 'npm run lint'
         publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: '', reportFiles: 'quality.html', reportName: 'Quality Report', reportTitles: ''])
     }
   }
   
   stage("Unit Test"){
     dir('react-frontend') {
         sh 'npm run test -- --coverage'
         publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'coverage/lcov-report', reportFiles: 'index.html', reportName: 'Coverage Report', reportTitles: ''])
     }
   }
   
   stage("Build"){
     dir('react-frontend') {
         sh 'npm run build'
     }
   }
   
   
}
